version: 2.1 

executors:
  my-executor:
    docker:
      - image: stsiwo/circleci-base:1.04 
    working_directory: /app

jobs:
  build:
    executor: my-executor
    steps:
      - run:
          name: Create GCloud Service Key File 
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            # gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet config set compute/zone us-central1-a 
            echo "test!!!!!!!!!!!!!!!! modified!!!!!!!!1!!!!" > test.txt
            gcloud info
            # gcloud compute scp --quiet ./test.txt circleci-container@$GOOGLE_COMPUTE_NAME:~ --zone $GOOGLE_COMPUTE_ZONE 
            gcloud compute scp --quiet ./test.txt nirnirva_s_t_s1551_gmail_com@my-8th-startup-test:~ --zone us-central1-a

