version: 2.1 

executors:
  my-executor:
    docker:
      - image: stsiwo/circleci-base:1.04 
    working_directory: /app

jobs:
  build:
    executor: my-executor
    steps:
      - run:
          name: Create GCloud Service Key File 
          command: |
            echo $GCLOUD_SERVICE_KEY > gcp-service-key.json
            gcloud auth activate-service-account --key-file ./gcp-service-key.json 
            rm -f ./gcp-service-key.json
            echo "test" > test.txt
            gcloud compute scp --quiet ./test.txt my-first-gce:~ --zone us-west1-a

