version: 2.1 

executors:
  my-executor:
    docker:
      - image: stsiwo/circleci-base:1.0 
        # working_directory: /tmp

jobs:
  build:
    executor: my-executor
    steps:
      - run:
          name: Build 
          command: |
            echo $GCLOUD_SERVICE_KEY
            gcloud auth activate-service-account --key-file $GCLOUD_SERVICE_KEY
            echo 'Build'

